steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'npm'
    args: ['install']

  # Build the Next.js app
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Optional: Run tests (uncomment if you have tests configured)
  # - name: 'gcr.io/cloud-builders/npm'
  #   entrypoint: 'npm'
  #   args: ['run', 'test']

artifacts:
  # Optional: Store the built artifacts (if using static export or deploying to Firebase/Cloud Run)
  objects:
    location: 'gs://$PROJECT_ID-cloudbuild-artifacts/'
    paths: ['.next/**', 'public/**', 'package.json']

    
timeout: 900s
